### PR TITLE
oc client version links updated in _modules.yml

### PR DESCRIPTION
**Pull request by kmurudi**

### CODE REVIEW

**Comment by jorgemoralespou** [comment]
@kmurudi The _modules.yml was updated with correct links from previous PR, but the install.adoc can remain. If you remove the _modules.yml I'll merge it.

Or, you can close the PR, and I'll add it. I'd rather have your contribution, but it's up to you.

**Comment by kmurudi** [comment]
Hi Jorge,

So, I'll remove the _modules.yml folder from my local repo and then submit
a PR?



Regards,
Kshitija Murudi


On Mon, Jun 26, 2017 at 5:34 AM, Jorge Morales Pou <notifications@github.com

**Comment by jorgemoralespou** [comment]
Yes, but if you can squash the commit, then it'll be easier. Else, you can just open a new PR with just the change in install.adoc (That's what I usually do as I'm no git expert).

**Comment by jorgemoralespou** [comment]
@kmurudi Still you have deleted the file, which will delete it in our repo.

I would just recommend you doing a new PR with the only change in install.adoc

**Comment by kmurudi** [comment]
Sure, I shall do that and submit a new PR

**Comment by jorgemoralespou** [comment]
This has already been fixed

**Pull request closed without merging**
