### PR TITLE
The configmap and pipeline modules needed GitHub support

### PR DESCRIPTION
**Pull request by gregswift**

### CODE REVIEW

**Comment by gregswift** [comment]
Oh and the environment page 😁

**Comment by jorgemoralespou** [comment]
Can you rebase this with the latest changes? There's now a GIT_SERVER variable

**Comment by rackergs** [comment]
wait.. so now there is GIT_HOST and GIT_SERVER that do the same thing ?

**Comment by rackergs** [comment]
@jorgemoralespou this one should be good to go

**Comment by jorgemoralespou** [comment]
Not relevant anymore

**Pull request closed without merging**
