### PR TITLE
add link to mlbparks app /ws/info/ endpoint

### PR DESCRIPTION
**Pull request by nickboldt**
add link to mlbparks app /ws/info/ endpoint

### CODE REVIEW

**Comment by marekjelen** [comment]
@siamaksade lgtm, as there is no handler for `/` it confuses people with error response page

**Comment by jorgemoralespou** [comment]
@nickboldt This is the URL for the info, to know if the mlbparks app has been deployed. The instructions are telling you to go to the map, since you should now see a new map showing up.

This can not be merged as it changes the intent of the workflow.
You can either rewrite it to better show that in that URL you can see that the backend has been deployed, but you still need to go to the parksmap app to see the map in action, or you can just close the issue, and I'll udpate it. In any case, I think the intent is good.

**Comment by nickboldt** [comment]
If you have a more clear solution than my PR, feel free to close this and suggest an alternative. I'm good with whatever makes it more user-friendly for the newb user.

**Comment by jorgemoralespou** [comment]
Not relevant anymore

**Pull request closed without merging**
